import { atom } from "recoil";

export const authUserState = atom({
  key: "authUserState",
  default: {},
});

export const campaignDumData = atom({
  key:"dummy",
  default:[
    {
      id: 0,
      campaign_id:0,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "리얼다시",
    },
    {
      id: 1,
      campaign_id:1,
      thumbnailImg: "",
      title : "지금 진행 중 어서와 업사이클은 처음이지?",
      desc : "고민하지 마시구~ 일단 들어와서 구경하세요~",
      status: "모집예정",
      recruitment:["2022.10.25","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:90,
      participating:0,
      userImg: "",
      userName: "노다지",
    },
    {
      id: 2,
      campaign_id:2,
      thumbnailImg: "",
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집마감",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 15,
      campaign_id:15,
      thumbnailImg: "",
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집마감",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 11,
      campaign_id:11,
      thumbnailImg: "",
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집예정",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 12,
      campaign_id:12,
      thumbnailImg: "",
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집예정",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 13,
      campaign_id:13,
      thumbnailImg: "",
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집예정",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 3,
      campaign_id:3,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 4,
      campaign_id:4,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 5,
      campaign_id:5,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 6,
      campaign_id:6,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 7,
      campaign_id:7,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 8,
      campaign_id:8,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 9,
      campaign_id:9,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 10,
      campaign_id:10,
      thumbnailImg: "",
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
  ]
})


export const commentDumData = atom({
  key:"dummyComment",
  default: [
    {
      campaign_id:0,
      userId:0,
      root_comment_id:"",
      content:"안녕하세요댓1~",
      userName: "도다시",
    },
    {
      campaign_id:0,
      userId:1,
      root_comment_id:"0",
      content:"안녕하세요 대댓1~",
      userName: "도다시",
    },
    {
      campaign_id:1,
      userId:2,
      root_comment_id:"",
      content:"안녕하세요댓2~",
      userName: "도다시",
    },
    {
      campaign_id:1,
      userId:3,
      root_comment_id:"2",
      content:"안녕하세요 대댓2~",
      userName: "도다시",
    },
    {
      campaign_id:0,
      userId:4,
      root_comment_id:"",
      content:"안녕하세요댓3   ~",
      userName: "도다시",
    },
    
  ]
})
