import { atom } from "recoil";

export const campaignDumData = atom({
  key:"dummy",
  default:[
    {
      id: 0,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 1,
      thumbnailImg: "",
      isLike : false,
      title : "지금 진행 중 어서와 업사이클은 처음이지?",
      desc : "고민하지 마시구~ 일단 들어와서 구경하세요~",
      status: "모집예정",
      recruitment:["2022.10.25","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:90,
      participating:0,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 2,
      thumbnailImg: "",
      isLike : false,
      title : "더미더미더미~ 더미 데이터~!",
      desc : "귀찮아서 쓰는 더미데이터 디스크립션~ 오션~",
      status: "모집마감",
      recruitment:["2022.09.28","2022.09.30"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:43,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 3,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 4,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 5,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 6,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 7,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 8,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 9,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
    {
      id: 10,
      thumbnailImg: "",
      isLike : false,
      title : "구해줘 지구! 업사이클 - 재활용품 다시 써봅시다!",
      desc : "누구나 함께 할 수 있습니다. 초보자 환영!, 남녀노소 캠페인 참여해주세요~",
      status: "모집 중",
      recruitment:["2022.09.28","2022.10.28"],
      progress:["2022.11.02","2022.11.30"],
      personnel:80,
      participating:76,
      userImg: "",
      userName: "도다시",
    },
  ]
})